# Generated by Django 5.2.8 on 2025-11-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=500)),
                ('icone', models.ImageField(blank=True, null=True, upload_to='midia/contato-<django.db.models.fields.AutoField>')),
            ],
        ),
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to='midia/curriculos/')),
                ('publico', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(max_length=300)),
                ('descricao', models.TextField(max_length=10000)),
                ('midia', models.ImageField(blank=True, null=True, upload_to='midia/projeto-<django.db.models.fields.AutoField>')),
                ('publico', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('profissao', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=5000)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='midia/sobre-<django.db.models.fields.AutoField>')),
                ('publico', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('icone', models.ImageField(blank=True, null=True, upload_to='midia/tecnologia-<django.db.models.fields.AutoField>')),
                ('publico', models.BooleanField(default=True)),
            ],
        ),
    ]
