# Generated by Django 5.2.8 on 2025-11-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='icone',
            field=models.ImageField(blank=True, null=True, upload_to='midia/contato-<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='midia',
            field=models.ImageField(blank=True, null=True, upload_to='midia/projeto-<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='midia/sobre-<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='tecnologias',
            name='icone',
            field=models.ImageField(blank=True, null=True, upload_to='midia/tecnologia-<django.db.models.fields.CharField>'),
        ),
    ]
