# Generated by Django 5.2.8 on 2025-11-24 20:29

import portfolio_admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_admin', '0002_alter_contato_icone_alter_projetos_midia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='icone',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio_admin.models.upload_contato),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='midia',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio_admin.models.upload_projeto),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio_admin.models.upload_sobre),
        ),
        migrations.AlterField(
            model_name='tecnologias',
            name='icone',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio_admin.models.upload_tecnologia),
        ),
    ]
