# Generated by Django 5.2.8 on 2025-11-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_admin', '0003_alter_contato_icone_alter_projetos_midia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnologias',
            name='descricao',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
