# Generated by Django 5.2.8 on 2025-11-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_admin', '0004_tecnologias_descricao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
